### ISSUE TITLE
Cannot instantiate ConfigInterface

### ISSUE THREAD

**Issue by JeroenVanLeusden** [cloudflare/Cloudflare-Magento#62]
### Preconditions
1. Cloudflare-Magento v1.1.6
2. Magento v2.1.4 (production mode)
3. PHP v7.0.22

### Related issues
https://github.com/cloudflare/Cloudflare-Magento/issues/34
https://github.com/cloudflare/Cloudflare-Magento/issues/38
https://github.com/cloudflare/Cloudflare-Magento/issues/39

### Summary
When running our deployment the following error is generated after running `di:compile` and `static-content:deploy`

```PHP
17:57:38 magento stderr: PHP Fatal error:  Uncaught Error: Cannot instantiate interface CF\Integration\ConfigInterface in deployment_acc/releases/20170829154850/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
17:57:38 Stack trace:
17:57:38 #0 deployment_acc/releases/20170829154850/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('CF\\Integration\\...', Array)
17:57:38 #1 deployment_acc/releases/20170829154850/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('CF\\Integration\\...')
17:57:38 #2 deployment_acc/releases/20170829154850/vendor/magento/framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('CF\\Integration\\...')
17:57:38 #3 deployment_acc/releases/20170829154850/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93
```

**Comment by JeroenVanLeusden** [comment]
Being installed correctly on Magento v2.1.9
