### ISSUE TITLE
Cannot instantiate interface CF\Integration\ConfigInterface

### ISSUE THREAD

**Issue by rwattogl** [cloudflare/Cloudflare-Magento#69]
```
[11-Apr-2018 13:58:00 UTC] PHP Fatal error:  Uncaught Error: Cannot instantiate interface CF\Integration\ConfigInterface in /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
Stack trace:
#0 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('CF\\Integration\\...', Array)
#1 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('CF\\Integration\\...')
#2 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('CF\\Integration\\...')
#3 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('CloudFlare\\Plug...')
#4 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Mage in /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111
```

Plugin v1.1.7
Magento v2.2.3

It's a clean install on a freshly configured CentOS 7.4 box with no other plugins or customisation (although I have disabled a number of the default plugins as follows; Magento_Weee Magento_Fedex Magento_Analytics Magento_Marketplace Magento_Signifyd Magento_Usps Magento_Braintree Magento_Dhl Dotdigitalgroup_Email Shopial_Facebook Temando_Shipping Magento_Ups Magento_SampleData Magento_Swagger Magento_Authorizenet).

Disabling the plugin causes the site to run fine again instantly.

**Comment by conflicker** [comment]
I got the same issue. It seems it's looking for CF_Integration module. Did you solve this issue? If so, may I know where to get CF_Integration module?

**Comment by rwattogl** [comment]
Unfortunately not, and since it was low priority for us it was put to the back of the queue. At some point I may revisit this and submit a PR or fix, but I wouldn't hold your breath.

**Comment by navarr** [comment]
Do you have cloudflare/cloudflare-plugin-backend installed?  Its one of the composer requirements
